apiVersion: v1
kind: Namespace
metadata:
  name: tools
---
apiVersion: v1
data:
  CEPHMONS: 192.168.10.1,192.168.10.6,192.168.10.11
  KEYRING: |
    [client.admin]
    key = AQDDOGdZWir6ORAA1qpeQBRwd+OER+vgizzsWQ==
    caps mds = "allow *"
    caps mon = "allow *"
    caps osd = "allow *"
kind: ConfigMap
metadata:
  name: ceph-dash-config
  namespace: tools
---
apiVersion: v1
data:
  auth: ZHByOiRhcHIxJFRKRDJQclFLJDJCYTZHQ3g2cXNBMDFzdGlLOGsvYi8K
kind: Secret
metadata:
  creationTimestamp: 2017-07-24T08:22:09Z
  name: basic-auth
  namespace: tools
type: Opaque

