apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: netdata-master-cfg
  namespace: monitoring
data:
  ND_1: "netdata.conf|global/memory mode = save"
  # The ip of the first node is hardcoded here. be careful!
  ND_2: "netdata.conf|global/bind to = 127.0.0.1:19999 192.168.10.1:19999"
  ND_3: "stream.conf|3a9757fe-5308-40c0-98b1-0a3d1b16b62e/enabled = yes"
  ND_4: "stream.conf|3a9757fe-5308-40c0-98b1-0a3d1b16b62e/history = 3600"
  ND_5: "stream.conf|3a9757fe-5308-40c0-98b1-0a3d1b16b62e/memory mode = save"
  ND_6: "stream.conf|3a9757fe-5308-40c0-98b1-0a3d1b16b62e/health enabled = yes"
  ND_7: "stream.conf|3a9757fe-5308-40c0-98b1-0a3d1b16b62e/postpone alarms on connect seconds = 60"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: netdata-slave-cfg
  namespace: monitoring
data:
  ND_1: "netdata.conf|global/memory mode = ram"
  ND_2: "netdata.conf|web/mode = none"
  ND_3: "stream.conf|stream/enabled = yes"
  ND_4: "stream.conf|stream/destination = 192.168.10.1:19999"
  ND_5: "stream.conf|stream/api key = 3a9757fe-5308-40c0-98b1-0a3d1b16b62e"
  ND_6: "stream.conf|stream/timeout seconds = 60"
  ND_7: "stream.conf|stream/buffer size bytes = 1048576"
  ND_8: "stream.conf|stream/reconnect delay seconds = 5"
  ND_9: "stream.conf|stream/initial clock resync iterations = 60"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: slave-mon-config
  namespace: monitoring
data:
  SM_SERVICES_MYSQL_RDSN: "clickyab_readonly:gX^Zmp90jOJp91$GwPujOTl2POQdlI@tcp(192.168.100.12:3306)/clickyab?charset=utf8&parseTime=true,clickyab_readonly:gX^Zmp90jOJp91$GwPujOTl2POQdlI@tcp(192.168.100.13:3306)/clickyab?charset=utf8&parseTime=true"
  SM_SERVICES_MYSQL_WDSN: "clickyab_master:oRgLsGydHQnZzvdNfHM6@tcp(192.168.100.11:3306)/clickyab?charset=utf8&parseTime=true"
  SM_SERVICES_MYSQL_REPLICATION_STATUS: "true"
  SM_SERVICES_MYSQL_REPLICATION_DELAY: "30"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: monitoring
data:
  SERVER_NAME: kibana.clickyab.ae
  ELASTICSEARCH_URL: http://192.168.110.1:9200
  ELASTICSEARCH_USERNAME: elastic
  ELASTICSEARCH_PASSWORD: Iumi5thidieLa6ee
---
apiVersion: v1          
kind: ConfigMap
metadata:
  name: ceph-dash-config
  namespace: monitoring
data:
  CEPHMONS: 192.168.10.1,192.168.10.6,192.168.10.11
  KEYRING: |
    [client.admin]
    key = AQDDOGdZWir6ORAA1qpeQBRwd+OER+vgizzsWQ==
    caps mds = "allow *"
    caps mon = "allow *"
    caps osd = "allow *"
