apiVersion: v1
kind: Namespace
metadata:
  name: docker-registry
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-registry
  namespace: docker-registry
  labels:
    k8s-app: kube-registry-upstream
    version: v0
spec:
  replicas: 1
  selector:
    k8s-app: kube-registry-upstream
    version: v0
  template:
    metadata:
      labels:
        k8s-app: kube-registry-upstream
        version: v0
    spec:
      containers:
      - name: registry
        image: registry:2
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: REGISTRY_HTTP_ADDR
          value: :5000
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /var/lib/registry
        volumeMounts:
        - name: image-store
          mountPath: /var/lib/registry
        ports:
        - containerPort: 5000
          name: registry
          protocol: TCP
      volumes:
      - name: image-store
        cephfs:
          monitors:
            - 192.168.100.60:6789
          user: admin
          secretRef:
            name: ceph-secret-registry
          path: "/docker-registry"
---
apiVersion: v1
kind: Service
metadata:
  name: kube-registry
  namespace: docker-registry
  labels:
    k8s-app: kube-registry-upstream
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "KubeRegistry"
spec:
  selector:
    k8s-app: kube-registry-upstream
  ports:
  - name: registry
    port: 5000
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: registry-ingress
  namespace: docker-registry
  annotations:
    ingress.kubernetes.io/proxy-body-size: 4000m
spec:
  rules:
  - host: kregistry.clickyab.ae
    http:
      paths:
      - path: /
        backend:
          serviceName: kube-registry
          servicePort: 5000