apiVersion: v1
kind: Namespace
metadata:
  name: docker-registry
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-registry
  namespace: docker-registry
  labels:
    k8s-app: kube-registry-upstream
    version: v0
spec:
  replicas: 1
  selector:
    k8s-app: kube-registry-upstream
    version: v0
  template:
    metadata:
      labels:
        k8s-app: kube-registry-upstream
        version: v0
    spec:
      containers:
      - name: registry
        image: registry:2
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: REGISTRY_HTTP_ADDR
          value: :5000
        - name: REGISTRY_STORAGE
          value: s3
        - name: REGISTRY_STORAGE_S3_ACCESSKEY
          value: clickyab
        - name: REGISTRY_STORAGE_S3_SECRETKEY
          value: Aewie6covoT3Aiqu
        - name: REGISTRY_STORAGE_S3_REGIONENDPOINT
          value: http://minio-service.minio:9000
        - name: REGISTRY_STORAGE_S3_REGION
          value: us-east-1
        - name: REGISTRY_STORAGE_S3_BUCKET
          value: docker
        - name: REGISTRY_STORAGE_S3_ENCRYPT
          value: "false"
        - name: REGISTRY_STORAGE_S3_SECURE
          value: "false"
        - name: REGISTRY_STORAGE_S3_V4AUTH
          value: "true"
        - name: REGISTRY_STORAGE_DELETE_ENABLED
          value: "true"
        - name: REGISTRY_STORAGE_S3_CHUNKSIZE
          value: "5242880"
        - name: REGISTRY_HTTP_SECRET
          value: "diha6oQuTaha2IepOhToo6ietied4ieVBiBoo6olAgiep4wuPha5aeCiEC1haigh"
        ports:
        - containerPort: 5000
          name: registry
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: kube-registry
  namespace: docker-registry
  labels:
    k8s-app: kube-registry-upstream
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "KubeRegistry"
spec:
  selector:
    k8s-app: kube-registry-upstream
  ports:
  - name: registry
    port: 5000
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: registry-ingress
  namespace: docker-registry
  annotations:
    ingress.kubernetes.io/proxy-body-size: 200m
spec:
  rules:
  - host: kregistry.clickyab.ae
    http:
      paths:
      - path: /
        backend:
          serviceName: kube-registry
          servicePort: 5000