apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: crane
    proc: worker
    spec: impression
  name: crane-impression-worker
  namespace: crane-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crane
      proc: worker
      spec: impression
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: crane
        proc: worker
        spec: impression
    spec:
      containers:
      - command:
        - /app/bin/impression-worker
        envFrom:
        - configMapRef:
            name: crane-config
        image: registry.clickyab.ae/clickyab/crane_dev:498
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 180
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 15
        name: crane-dev
        ports:
        - containerPort: 9000
          name: web-health
          protocol: TCP
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /healthz
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 15
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regsecret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
