apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # This name uniquely identifies the Deployment
  name: legacy-crontabs
  namespace: legacy
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        # Label is used as selector in the service.
        app: crontabs
        proc: cron
        k8s-app: legacy-crontabs
        lang: php
        branch: master
    spec:
      containers:
      - name: legacy-crontabs
        image: registry.clickyab.ae/clickyab/crontabs:master.4
        envFrom:
        - configMapRef:
            name: legacy-config
---