apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: front-ingress
  namespace: legacy
spec:
  rules:
  - host: a.clickyab.com
    http:
      paths:
      - path: /
        backend:
          serviceName: front-legecy-service
          servicePort: 9000
  - host: app.clickyab.com
    http:
      paths:
      - path: /
        backend:
          serviceName: front-legecy-service
          servicePort: 9000