apiVersion: v1
kind: ConfigMap
metadata:
  name: jabeh-staging-beanstalkd-config
  namespace: jabeh-staging
data:
  BEANSTALK_HOST: 127.0.0.1
  BEANSTALK_PORT_11300_TCP_ADDR: 127.0.0.1
  QUEUE_DRIVER: beanstalkd
