apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jabeh-staging-elasticsearch
  namespace: jabeh-staging
  labels:
    k8s-app: jabeh-staging
    service: searchd
    namespace: jabeh-staging
    branch: dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
        namespace: jabeh-staging
        service: searchd
        branch: dev
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: elasticsearch
          image: elasticsearch
          ports:
            - name: elasticsearch
              containerPort: 9200
