apiVersion: v1
kind: Service
metadata:
  name: jabeh-staging-mysqld-service
  namespace: jabeh-staging
  labels:
    k8s-app: jabeh
    service: mysqld
    branch: dev
    type: db
    namespace: jabeh-staging
spec:
  selector:
    k8s-app: jabeh
    service: mysqld
    type: db
    namespace: jabeh-staging
  ports:
    - name: mysqld
      port: 3306
      protocol: TCP
