apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jabeh-staging-beanstalkd
  namespace: jabeh-staging
  labels:
    k8s-app: jabeh
    service: beanstalkd
    service: beanstalkd-console
    namespace: jabeh-staging
    branch: dev
    type: queued
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: beanstalkd
        service: beanstalkd
        service: beanstalkd-console
        namespace: jabeh-staging
        type: queued
        branch: dev
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: jabeh-staging-beanstalkd
          image: mehrdadkhah/beanstalkd
          envFrom:
            - configMapRef:
                name: jabeh-staging-beanstalkd-config
        - name: jabeh-staging-beanstalkd-console
          image: agaveapi/beanstalkd-console
          envFrom:
            - configMapRef:
                name: jabeh-staging-beanstalkd-config
