apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jabeh-dev
  namespace: jabeh-staging
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jabeh
        service: app
        k8s-app: jabeh-dev-app
    spec:
      imagePullSecrets:
        - name: regsecret
      containers:
      - name: jabeh-dev
        image: registry.clickyab.ae/clickyab/jabeh:dev.765
        envFrom:
          - configMapRef:
              name: jabeh-staging-config
        ports:
        - name: web
          containerPort: 80
        volumeMounts:
        - name: cdn
          mountPath: /cdn
        - name: chunks
          mountPath: /chunks
        - name: cachethumb
          mountPath: /tmp/thumbnails
        - name: cachevideo
          mountPath: /tmp/videos
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 80
            scheme: HTTP
          initialDelaySeconds: 180
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 15
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /healthz
            port: 80
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 15
      volumes:
      - name: cdn
        cephfs:
          monitors:
            - 192.168.10.1:6789
            - 192.168.10.6:6789
            - 192.168.10.11:6789
          user: admin
          secretRef:
            name: ceph-secret
          path: "/jabeh/cdn"
      - name: chunks
        cephfs:
          monitors:
            - 192.168.10.1:6789
            - 192.168.10.6:6789
            - 192.168.10.11:6789
          user: admin
          secretRef:
            name: ceph-secret
          path: "/jabeh/chunks"
      - name: cachethumb
        emptyDir: {}
      - name: cachevideo
        emptyDir: {}
