apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: jabeh-staging
    namespace: jabeh-staging
    service: redis
  name: jabeho-staging-redis
  namespace: jabeh-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      branch: dev
      namespace: jabeh-staging
      service: redis
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis
        branch: dev
        namespace: jabeh-staging
        service: redis
    spec:
      containers:
      - image: redis
        imagePullPolicy: Always
        name: redis
        ports:
        - containerPort: 6379
          name: redis
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
