apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: jabeh
    branch: dev
    k8s-app: jabeh-dev-reporter
    lang: php
    proc: worker
  name: jabeh-dev-reporter
  namespace: jabeh-staging
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jabeh
        branch: dev
        k8s-app: jabeh-dev-reporter
        lang: php
        proc: worker
    spec:
      imagePullSecrets:
        - name: regsecret
      containers:
      - command:
        - php
        - /app/artisan
        - queue:work
        - --queue=ExcelReport
        - --sleep=5
        - --tries=5
        - --daemon
        envFrom:
        - configMapRef:
            name: jabeh-staging-config
        image: registry.clickyab.ae/clickyab/jabeh:dev.735
        name: jabeh-dev
        resources:
          limits:
            cpu: "1"
            memory: 800Mi
          requests:
            memory: 500Mi
        volumeMounts:
        - mountPath: /cdn
          name: cdn
        - mountPath: /chunks
          name: chunks
        - mountPath: /tmp/thumbnails
          name: cachethumb
        - mountPath: /tmp/videos
          name: cachevideo
      terminationGracePeriodSeconds: 30
      volumes:
      - cephfs:
          monitors:
          - 192.168.10.1:6789
          - 192.168.10.6:6789
          - 192.168.10.11:6789
          path: /jabeh/cdn
          secretRef:
            name: ceph-secret
          user: admin
        name: cdn
      - cephfs:
          monitors:
          - 192.168.10.1:6789
          - 192.168.10.6:6789
          - 192.168.10.11:6789
          path: /jabeh/chunks
          secretRef:
            name: ceph-secret
          user: admin
        name: chunks
      - emptyDir:
          sizeLimit: "0"
        name: cachethumb
      - emptyDir:
          sizeLimit: "0"
        name: cachevideo
