apiVersion: v1
kind: Service
metadata:
  name: jabeh-staging-beanstalkd-service
  namespace: jabeh-staging
  labels:
    k8s-app: jabeh
    service: beanstalkd
    namespace: jabeh-staging
    branch: dev
    type: queued
spec:
  selector:
    app: beanstalkd
    # service: beanstalkd
    # namespace: jabeh-staging
  ports:
    - name: beanstalkd
      port: 11300
      protocol: TCP
    - name: beanstalkd-console
      port: 80
      protocol: TCP
