apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    branch: dev
    k8s-app: jabeh-staging
    namespace: jabeh-staging
    service: searchd
  name: jabeh-staging-elasticsearch
  namespace: jabeh-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
      branch: dev
      namespace: jabeh-staging
      service: searchd
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: elasticsearch
        branch: dev
        namespace: jabeh-staging
        service: searchd
    spec:
      containers:
      - image: elasticsearch
        imagePullPolicy: Always
        name: elasticsearch
        ports:
        - containerPort: 9200
          name: elasticsearch
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
