---
apiVersion: v1
data:
  disable-access-log: "true"
  enable-vts-status: "true"
  use-proxy-protocol: "false"
  proxy-read-timeout: "240"
  proxy-send-timeout: "240"
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: tcp-services
  namespace: ingress-nginx
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: udp-services
  namespace: ingress-nginx
