apiVersion: v1
data:
  APP_DEBUG: "true"
  APP_KEY: UQxSeqPYW8m1uZsJL3vdBNbVcALY7mHO
  DB_DATABASE: clickyab
  DB_HOST: 192.168.100.11
  DB_PASSWORD: dicnm7alZQUhUIOi
  DB_USERNAME: clickyab_console
  GIT_REV: 8f589911e92fefa4b878321e0543b09f3143269b
  MAIL_HOST: smtp.sendgrid.net
  MAIL_PASSWORD: sendg78u9i0o@789
  MAIL_PORT: "587"
  MAIL_USERNAME: clickyab
  NO_VHOST: "0"
  PORT: "9000"
  TIMEZONE: Asia/Tehran
  TZ: Asia/Tehran
  WEB_CONCURRENCY: "8"
kind: ConfigMap
metadata:
  name: console-master-config
  namespace: console
