apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # This name uniquely identifies the Deployment
  name: statics
  namespace: console
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        # Label is used as selector in the service.
        app: nginx
        proc: webserver
        k8s-app: statics-webserver
    spec:
      containers:
      - name: statics
        image: nginx:alpine
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
            scheme: HTTP
          initialDelaySeconds: 180
          timeoutSeconds: 15
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
            scheme: HTTP
          initialDelaySeconds: 1
          timeoutSeconds: 15
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 1
        ports:
        - name: statics
          containerPort: 80
        volumeMounts:
        - name: statics
          mountPath: /usr/share/nginx/html
          readOnly: true
      volumes:
      - name: statics
        cephfs:
          monitors:
            - 192.168.10.1:6789
            - 192.168.10.6:6789
          user: admin
          secretRef:
            name: ceph-secret
          path: "/legacy/statics"
