kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: nodemon
rules:
  - apiGroups:
      - ""
    resources:
      - nodes/status
    verbs:
      - patch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: nodemon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nodemon
subjects:
- kind: ServiceAccount
  name: nodemon
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nodemon
  namespace: kube-system
