---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: node-problem-detector
  namespace: kube-system
  labels:
      k8s-app: node-problem-detector
      version: v0.4
      kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: node-problem-detector
        version: v0.4
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccountName: nodemon
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: node-problem-detector
        image: gcr.io/google_containers/node-problem-detector:v0.4.1
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
          - name: log
            mountPath: /log
            readOnly: true
          - name: localtime
            mountPath: /etc/localtime
            readOnly: true
          - name: docker-sock
            mountPath: /var/run/docker.sock
          - name: docker-gc
            mountPath: /var/lib/docker-gc
      volumes:
        - name: log
          # Config `log` to your system log directory
          hostPath:
            path: /var/log/
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: docker-gc
          hostPath:
            path: /var/lib/docker-gc