kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: nodemon
rules:
  - apiGroups:
      - ""
    resources:
      - nodes/status
    verbs:
      - patch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: nodemon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nodemon
subjects:
- kind: ServiceAccount
  name: nodemon
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nodemon
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: node-problem-detector
  namespace: kube-system
  labels:
      k8s-app: node-problem-detector
      version: v0.4
      kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: node-problem-detector
        version: v0.4
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccountName: nodemon
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: node-problem-detector
        image: registry.clickyab.ae/clickyab/health-check:0.4.1
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
          - name: log
            mountPath: /log
            readOnly: true
          - name: localtime
            mountPath: /etc/localtime
            readOnly: true
          - name: docker-sock
            mountPath: /var/run/docker.sock
          - name: docker-gc
            mountPath: /var/lib/docker-gc
      volumes:
        - name: log
          # Config `log` to your system log directory
          hostPath:
            path: /var/log/
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: docker-gc
          hostPath:
            path: /var/lib/docker-gc