---
apiVersion: v1
kind: Service
metadata:
  name: fluentd
  namespace: elasticsearch
  labels:
    k8s-app: fluentd
spec:
  selector:
    k8s-app: fluentd
  ports:
  - name: loggert
    port: 24224
    protocol: TCP
  - name: loggeru
    port: 24224
    protocol: UDP