apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # This name uniquely identifies the Deployment
  name: jabeh-benstalkd-console
  namespace: jabeh
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        # Label is used as selector in the service.
        app: jabeh
        proc: webserver
        k8s-app: jabeh-benstalkd-console
        lang: php
        branch: master
    spec:
      containers:
      - name: jabeh-bc
        image: agaveapi/beanstalkd-console
        envFrom:
        - configMapRef:
            name: jabeh-master-config