apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # This name uniquely identifies the Deployment
  name: jabeh-master
  namespace: jabeh
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        # Label is used as selector in the service.
        app: jabeh
        proc: webserver
        k8s-app: jabeh-master-webserver
        lang: php
        branch: master
    spec:
      containers:
      - name: jabeh-master
        image: registry.clickyab.ae/clickyab/jabeh:master.67
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 15
          periodSeconds: 60
        command: [ "/bin/herokuish", "procfile","start", "web"]
        envFrom:
        - configMapRef:
            name: jabeh-master-config
        ports:
        - name: master-web
          containerPort: 9000
        volumeMounts:
        - name: cdn
          mountPath: /cdn
        - name: chunks
          mountPath: /chunks
        - name: cachethumb
          mountPath: /tmp/thumbnails
        - name: cachevideo
          mountPath: /tmp/videos
      volumes:
      - name: cdn
        cephfs:
          monitors:
            - 192.168.10.1:6789
            - 192.168.10.6:6789
            - 192.168.10.11:6789
          user: admin
          secretRef:
            name: ceph-secret
          path: "/jabeh/cdn"
      - name: chunks
        cephfs:
          monitors:
            - 192.168.10.1:6789
            - 192.168.10.6:6789
            - 192.168.10.11:6789
          user: admin
          secretRef:
            name: ceph-secret
          path: "/jabeh/chunks"
      - name: cachethumb
        emptyDir: {}
      - name: cachevideo
        emptyDir: {}