apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: jabeh
    branch: master
    k8s-app: jabeh-master-webserver
    lang: php
    proc: webserver
  name: jabeh-master
  namespace: jabeh
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jabeh
        branch: master
        k8s-app: jabeh-master-webserver
        lang: php
        proc: webserver
    spec:
      imagePullSecrets:
        - name: regsecret
      containers:
      - command:
        - /bin/herokuish
        - procfile
        - start
        - web
        envFrom:
        - configMapRef:
            name: jabeh-master-config
        image: registry.clickyab.ae/clickyab/jabeh:master.402
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 180
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 15
        name: jabeh-master
        ports:
        - containerPort: 9000
          name: master-web
          protocol: TCP
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /healthz
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 15
        resources:
          limits:
            memory: 1524Mi
          requests:
            memory: 1Gi
        volumeMounts:
        - mountPath: /cdn
          name: cdn
        - mountPath: /chunks
          name: chunks
        - mountPath: /tmp/thumbnails
          name: cachethumb
        - mountPath: /tmp/videos
          name: cachevideo
      terminationGracePeriodSeconds: 30
      volumes:
      - cephfs:
          monitors:
          - 192.168.10.1:6789
          - 192.168.10.6:6789
          - 192.168.10.11:6789
          path: /jabeh/cdn
          secretRef:
            name: ceph-secret
          user: admin
        name: cdn
      - cephfs:
          monitors:
          - 192.168.10.1:6789
          - 192.168.10.6:6789
          - 192.168.10.11:6789
          path: /jabeh/chunks
          secretRef:
            name: ceph-secret
          user: admin
        name: chunks
      - emptyDir:
          sizeLimit: "0"
        name: cachethumb
      - emptyDir:
          sizeLimit: "0"
        name: cachevideo
