apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # This name uniquely identifies the Deployment
  name: jabeh-cdn-master
  namespace: jabeh
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        # Label is used as selector in the service.
        app: jabeh
        proc: webserver
        k8s-app: jabeh-master-cdn
        lang: php
        branch: master
    spec:
      containers:
      - name: jabeh-cdn
        image: nginx:1-alpine
        volumeMounts:
        - name: cdn
          mountPath: /usr/share/nginx/html
        ports:
        - name: master-cdn
          containerPort: 80
      volumes:
      - name: cdn
        cephfs:
          monitors:
            - 192.168.10.1:6789
            - 192.168.10.6:6789
            - 192.168.10.11:6789
          user: admin
          secretRef:
            name: ceph-secret
          path: "/jabeh/cdn"