apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mantis-hls-master
  labels:
    k8s-app: mantis-hls-master
  namespace: jabeh
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: mantis-hls-master
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: mantis-hls-master
        image: registry.clickyab.ae/clickyab/cluster-tools:master.12
        command: [ "/app/bin/mantis"]
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        envFrom:
        - configMapRef:
            name: jabeh-master-config
        volumeMounts:
        - name: cdn
          mountPath: /cdn
      volumes:
      - name: cdn
        cephfs:
          monitors:
            - 192.168.10.1:6789
            - 192.168.10.6:6789
            - 192.168.10.11:6789
          user: admin
          secretRef:
            name: ceph-secret
          path: "/jabeh/cdn"