
---
apiVersion: v1
kind: Service
metadata:
  name: jabeh-master-service
  namespace: jabeh
  labels:
    k8s-app: jabeh-web-service
spec:
  selector:
    k8s-app: jabeh-master-webserver
  ports:
  - name: mster
    port: 9000
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: jabeh-cdn-master-service
  namespace: jabeh
  labels:
    k8s-app: jabeh-cdn-service
spec:
  selector:
    k8s-app: jabeh-master-cdn
  ports:
  - name: cdn
    port: 80
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: jabeh-benstalkd
  namespace: jabeh
  labels:
    k8s-app: jabeh-beanstalkd
spec:
  selector:
    k8s-app: jabeh-beanstalkd
  ports:
  - name: bst
    port: 80
    protocol: TCP
  - name: bst2
    port: 11300
    protocol: TCP