apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jabeh-beanstalkd
  namespace: jabeh
  labels:
    k8s-app: jabeh-beanstalkd
    service: beanstalkd
    service: beanstalkd-console
    namespace: jabeh
    branch: master
    type: queued
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: beanstalkd
        service: beanstalkd
        service: beanstalkd-console
        namespace: jabeh
        type: queued
        branch: master
        k8s-app: jabeh-beanstalkd
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: jabeh-staging-beanstalkd
          image: mehrdadkhah/beanstalkd
          envFrom:
            - configMapRef:
                name: jabeh-master-config
        - name: jabeh-staging-beanstalkd-console
          image: agaveapi/beanstalkd-console
          envFrom:
            - configMapRef:
                name: jabeh-master-config
