apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  generation: 136
  labels:
    app: jabeh
    branch: master
    k8s-app: jabeh-master-convert-hls
    lang: php
    proc: worker
  name: jabeh-master-convert-hls
  namespace: jabeh
spec:
  replicas: 4
  selector:
    matchLabels:
      app: jabeh
      branch: master
      k8s-app: jabeh-master-convert-hls
      lang: php
      proc: worker
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jabeh
        branch: master
        k8s-app: jabeh-master-convert-hls
        lang: php
        proc: worker
    spec:
      containers:
      - command:
        - php
        - /app/artisan
        - queue:work
        - --queue=ConvertToHls
        - --sleep=5
        - --tries=5
        - --daemon
        envFrom:
        - configMapRef:
            name: jabeh-master-config
        image: registry.clickyab.ae/clickyab/jabeh:master.982
        name: jabeh-master
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 1424Mi
        volumeMounts:
        - mountPath: /cdn
          name: cdn
        - mountPath: /chunks
          name: chunks
        - mountPath: /tmp/thumbnails
          name: cachethumb
        - mountPath: /tmp/videos
          name: cachevideo
      imagePullSecrets:
      - name: regsecret
      restartPolicy: Always
      volumes:
      - cephfs:
          monitors:
          - 192.168.10.1:6789
          - 192.168.10.6:6789
          - 192.168.10.11:6789
          path: /jabeh/cdn
          secretRef:
            name: ceph-secret
          user: admin
        name: cdn
      - cephfs:
          monitors:
          - 192.168.10.1:6789
          - 192.168.10.6:6789
          - 192.168.10.11:6789
          path: /jabeh/chunks
          secretRef:
            name: ceph-secret
          user: admin
        name: chunks
      - emptyDir: {}
        name: cachethumb
      - emptyDir: {}
        name: cachevideo
