apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: jabeh
    branch: master
    k8s-app: jabeh-master-elasticsearch
    proc: queued
  name: elasticsearch
  namespace: jabeh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jabeh
      branch: master
      k8s-app: jabeh-master-elasticsearch
      proc: queued
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jabeh
        branch: master
        k8s-app: jabeh-master-elasticsearch
        proc: queued
    spec:
      containers:
      - image: elasticsearch
        imagePullPolicy: Always
        name: elasticsearch
        ports:
        - containerPort: 9200
          name: elastic-port
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
