apiVersion: v1
kind: Service
metadata:
  name: jabeh-beanstalkd
  namespace: jabeh
  labels:
    k8s-app: jabeh-beanstalkd
spec:
  selector:
    k8s-app: jabeh-beanstalkd
  ports:
  - name: bst
    port: 80
    protocol: TCP
  - name: bst2
    port: 11300
    protocol: TCP
