apiVersion: v1
kind: Service
metadata:
  name: jabeh-cdn-master-service
  namespace: jabeh
  labels:
    k8s-app: jabeh-cdn-service
spec:
  selector:
    k8s-app: jabeh-master-cdn
  ports:
  - name: cdn
    port: 80
    protocol: TCP
