apiVersion: v1
kind: Service
metadata:
  name: jabeh-master-service
  namespace: jabeh
  labels:
    k8s-app: jabeh-web-service
spec:
  selector:
    k8s-app: jabeh-master-webserver
  ports:
  - name: mster
    port: 9000
    protocol: TCP
