apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: jabeh-6hours-cron
  namespace: jabeh
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 12
  jobTemplate:
    spec:
      activeDeadlineSeconds: 1200
      template:
        spec:
          imagePullSecrets:
            - name: regsecret
          containers:
          - command:
            - php
            - artisan
            - check:new-videos-state
            envFrom:
            - configMapRef:
                name: jabeh-master-config
            image: registry.clickyab.ae/clickyab/jabeh:master.831
            imagePullPolicy: IfNotPresent
            name: jabeh-cron-6hours
          restartPolicy: Never
  schedule: 16 * * * *
  successfulJobsHistoryLimit: 6
  suspend: false
