apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: jabeh
    branch: master
    k8s-app: jabeh-master-cdn
    lang: php
    proc: webserver
  name: jabeh-cdn-master
  namespace: jabeh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jabeh
      branch: master
      k8s-app: jabeh-master-cdn
      lang: php
      proc: webserver
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jabeh
        branch: master
        k8s-app: jabeh-master-cdn
        lang: php
        proc: webserver
    spec:
      containers:
      - image: registry.clickyab.ae/clickyab/jabeh-nginx:alpine
        imagePullPolicy: IfNotPresent
        name: jabeh-cdn
        ports:
        - containerPort: 80
          name: master-cdn
          protocol: TCP
        resources:
          limits:
            memory: 3Gi
          requests:
            memory: 2560Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: cdn
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regsecret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - cephfs:
          monitors:
          - 192.168.10.1:6789
          - 192.168.10.6:6789
          - 192.168.10.11:6789
          path: /jabeh/cdn
          secretRef:
            name: ceph-secret
          user: admin
        name: cdn
