apiVersion: v1
data:
  GAD_AMQP_DSN: amqp://gad:eeTheej2@rabbitmq.rabbitmq:5672/gad
  GAD_CLICKYAB_ACCEPTED_DEMANDS: clickyab:clickyab:30708
  GAD_CLICKYAB_AD_CTR_EFFECT: "70"
  GAD_CLICKYAB_FAKE_SUPPLIER: none
  GAD_CLICKYAB_FLOOR_DIV_APP: "3"
  GAD_CLICKYAB_FLOOR_DIV_NATIVE: "3"
  GAD_CLICKYAB_FLOOR_DIV_VAST: "3"
  GAD_CLICKYAB_NATIVE_MAX_COUNT: "12"
  GAD_CLICKYAB_SLOT_CTR_EFFECT: "30"
  GAD_CLICKYAB_UNDER_FLOOR: "true"
  GAD_DEVEL_MODE: "false"
  GAD_FLUENTD_ALL_LEVELS: "true"
  GAD_FLUENTD_ENABLE: "true"
  GAD_FLUENTD_HOST: fluentd.monitoring
  GAD_FLUENTD_PORT: "24224"
  GAD_FLUENTD_TAG: log.gad
  GAD_MYSQL_DATABASE: clickyab
  GAD_MYSQL_MAX_CONNECTION: "10"
  GAD_MYSQL_MAX_IDLE_CONNECTION: "3"
  GAD_MYSQL_RDSN: clickyab_readonly:gX^Zmp90jOJp91$GwPujOTl2POQdlI@tcp(192.168.100.13:3306)/clickyab?charset=utf8&parseTime=true,clickyab_readonly:gX^Zmp90jOJp91$GwPujOTl2POQdlI@tcp(192.168.100.12:3306)/clickyab?charset=utf8&parseTime=true
  GAD_MYSQL_WDSN: clickyab_master:oRgLsGydHQnZzvdNfHM6@tcp(192.168.100.11:3306)/clickyab?charset=utf8&parseTime=true
  GAD_PROFILE: disable
  GAD_PROTO: http
  GAD_REDIS_ADDRESS: 192.168.120.1:2222
  GAD_REDIS_DATABASE: "7"
  GAD_REDIS_PASSWORD: bita123
  GAD_REDIS_SIZE: "250"
  GAD_SITE: a.clickyab.com
  PORT: "9000"
kind: ConfigMap
metadata:
  name: gad-dev-config
  namespace: gad
