apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: gad
    proc: worker
    spec: imp
  name: gad-impression
  namespace: gad
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gad
        proc: worker
        spec: imp
    spec:
      imagePullSecrets:
        - name: regsecret
      containers:
      - command:
        - /app/bin/impworker
        envFrom:
        - configMapRef:
            name: gad-config
        image: registry.clickyab.ae/clickyab/gad:master.343
        name: gad-master
        resources:
          limits:
            memory: 200Mi
          requests:
            memory: 100Mi
      terminationGracePeriodSeconds: 30
