apiVersion: v1
kind: Namespace
metadata:
  name: global
---
apiVersion: v1
kind: Secret
metadata:
  name: git-sync-creds
  namespace: global
type: Opaque
data:
  ssh: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBdDdMWFpybEl2TENUNlBhTXNkUmp5OUJPMjRLVEdnNUFSQnlSQlVWU3k3NGIrOVVMCkttK3p6Y3JnUXM2cHJ5SHFwc3JTdDF2YU9waktycUZEbnNSRUxwanNMUURwK01yUU44TFgxa01NaCt5MEVZRTYKMHI5RGhkSGN6ZEFtU2d4N3prSDh3bVJJYzVWbXV3ckZHV1Btblp5YVk5Nk4rNWJrMzg2S2RSU0hiVEJOSkhMRApvZ0Z0WVlXem9qSFlyZ0lWL0VaRC9RcUp6TkE1V0tqQmhIMmVVNHJFMXhySWJKSWJPeXdIeGlyODQwbTUvT041CnRYYXQzZmw1MkNsQlF0WXlKQ3lPVFV0bk9oS3VMTTRFc0RFTmtkY2ZEWkJSWlVDUVhTenZuTmdSQzlmb0lRMDQKTFlpSWhFaHFTU1QzMHJDalBmVmtaL0YwRDF4Mm5JdGI2S2dIbndJREFRQUJBb0lCQVFDRmc1M2RVcFBVV1A3WQpGc0tCeVozVEdBOElxbW5pU1ROYWpleTFpUUk1aFc1dlpoUGNmeDJQV0lJUTdJWVYvUy9BbEsvOGh1MGhJOFpFCmtIOUdXTjQ1Zy9vOFoycW00am5lSFdha20wenpTZzVDbnN1ek8wS0hjOVhwWFAxSFdyVnRYemFuengxOXJMdmkKL0Z2dkxWWURmandVbEVCYitQdFcwNVo4ckRRV0hnYlpKQUUwWGNiTWNNT2ZVSy9rNmNtMGZsYWc0bkpURXBnQQpZdWlsM2VKQkxNdW01QmVmeVdQZzBzSEZ5dWZtTWxyMzlaSEUrZHcyOWk1MlJ4azZKblgvRDJiUWFwbWhtL082Ck9ybE1hNmM5bTM5U0ZyN2lXaTYxREtSVzNleGhWRmlXZWhlZUdmWGZXaVFsUnVEM1h6N3dPZHdFRk5vWEpDT1UKcGF4dkdFeXBBb0dCQU4wUm5FeHZZU1Rhb3JPalB2QVd3eGY4eUtkaS9YWmd1WmZLRzFmcTNQOUFEZDJtZDV1ZwpIK3NWbXVycDJNK2ZzcnVEMklvOUFWcit1c3RWd0Vqbzl6alN5WmJ2NHFYT1d3ajBzanhmVnAvWHVubVEzQUl5Cm9YVGxpcG9CVVBHc2NTK2Z3UjZMYUxqaCs0NHQyY0dlMlg1SHRNR3hkNU1PMmd0YVZjVUhDSTZqQW9HQkFOUzUKbElEaFp3dDNoZ25JUkk1Q2RmbC9nNzVJTnR4a0JEWm9NM01tMDZ3aXVzQytONTZGcU05bWk2ME5zcFJjYnpZdQpzMlh6d3FaaGZlNVd5R2F0Q1ZtM1Y3bEE3WXFOV080WnpMb3JhTzJPYWZKNlhiamVnWXJSbkdJQTY1bjZZcEVWCnFQVjlQMG9LUzVnWXJTTklma0ZOMmZDVlNpdFIwQUYwRm9lM1NON1ZBb0dBVG9BNmFFb0V6UGwyWFNQUzdaNm4KbUpVREM2MXpJOTRsQ1dtVFhCemliU0ZweXhPWjFZRisxQlBQOXlzaStsZFRPSk1SQ2NXdi9ZZ0cvTDF1a25WbgpsSjRGUjd2WFY5bDNLaTc2TzhYL0ZMT2VYQnk4ZzJ0SE9pTm9uRmRyVHVaVkt2d25yNWtCanVWd1ZvU2hsc2U1Cm84WUN3ZVVxK09XRk9CTFQ4aXNWTnRFQ2dZQlRxTUI4aHlqdFc0NDlYcU9IaHgrNmhhbWNOZTVOY3BBdGpZRmUKY2hDaEMrK0NTY3k1N1RyY2hpbThYenl5R0VBc2dPVlEzVExhR0ZGY1lJamp5SDE2NlIzNDMwNE1SVmFLSFY5awpnQm4rQXhvcm9IQW5lbXBiMjkreXMwWDFBb0d0S1dXUFZqaUR0OVRPOWpWeFFOdFdkM1dVcGtITEU1dklWbzFkCnhubEVHUUtCZ0FpdmszWHRWQTJlNUlnRTlQdFg2MFpRTy9FeitRVTBCNFVsM2NLSGNUMHNFV3FiTTRLc1Z0ZFQKMGZzU04ySEg4c3hCd2NTMStaWEJYZzhkS1RUbkFiTVJjS2c5K3FzeVVVMnQrYVFBRkRuUTM0NldaS1N5NDlIawpyNGVzTzZLK25MYWRTQ1VXT0I3Sk8ybFFlTkpicDU5bzNSWGV0akE4ZEpZUVBSTDNzL1lnCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
  known_hosts: Z2l0aHViLmNvbSBzc2gtcnNhIEFBQUFCM056YUMxeWMyRUFBQUFCSXdBQUFRRUFxMkE3aFJHbWRubTl0VURiTzlJRFN3Qks2VGJRYStQWFlQQ1B5NnJiVHJUdHc3UEhrY2NLcnBwMHlWaHA1SGRFSWNLcjZwTGxWREJmT0xYOVFVc3lDT1Ywd3pmaklKTmxHRVlzZGxMSml6SGhibjJtVWp2U0FIUXFaRVRZUDgxZUZ6TFFOblBIdDRFVlZVaDdWZkRFU1U4NEtlem1ENVFsV3BYTG12VTMxL3lNZitTZTh4aEhUdktTQ1pJRkltV3dvRzZtYlVvV2Y5bnpwSW9hU2pCK3dlcXFVVW1wYWFhc1hWYWw3MkorVVgyQisyUlBXM1JjVDBlT3pRZ3FsSkwzUktyVEp2ZHNqRTNKRUF2R3EzbEdIU1pYeTI4RzNza3VhMlNtVmkvdzR5Q0U2Z2JPRHFuVFdsZzcrd0M2MDR5ZEdYQThWSmlTNWFwNDNKWGlVRkZBYVE9PQo=
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: git-sync-watcher
  namespace: global
  labels:
    tier: config
    app: git-sync
    version: v1
spec:
  template:
    metadata:
      labels:
        name: config
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
        - securityContext:
            runAsUser: 0
          resources:
            requests:
              cpu: 0.15
          image: gcr.io/google_containers/git-sync-amd64:v2.0.5
          name: git-sync-config
          env:
            - name: GIT_SYNC_REPO
              value: git@github.com:clickyab/server-configs.git
            - name: GIT_SYNC_DEST
              value: configs
            - name: GIT_SYNC_WAIT
              value: "600"
            - name: GIT_SYNC_SSH
              value: "true"
            - name: GIT_SYNC_SSH_KNOWN_HOSTS
              value: "true"
          volumeMounts:
            - name: credentials
              mountPath: /etc/git-secret
              readOnly: true
            - name: target-git
              mountPath: /git
      volumes:
        - name: target-git
          hostPath:
            path: /etc/global
        - name: credentials
          secret:
            secretName: git-sync-creds
            defaultMode: 256