kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: nodemon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nodemon
subjects:
- kind: ServiceAccount
  name: nodemon
  namespace: kube-system
