apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: crab
    k8s-app: testing
    proc: testing
  name: testing-pod
  namespace: ccc
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: crab
        k8s-app: testing
        proc: testing
    spec:
      imagePullSecrets:
        - name: regsecret
      containers:
      - command:
        - /sbin/my_init
        - --
        - bash
        - -c
        - while true; do sleep 100; done
        image: phusion/baseimage:0.9.22
        name: base
        ports:
        - containerPort: 9000
          name: testing-web
          protocol: TCP
      terminationGracePeriodSeconds: 30
