apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # This name uniquely identifies the Deployment
  name: testing-pod
  namespace: ccc
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        # Label is used as selector in the service.
        app: crab
        proc: testing
        k8s-app: testing
    spec:
      containers:
      - name: base
        image: phusion/baseimage:0.9.22
        command: ["/sbin/my_init",  "--",  "bash",  "-c", "while true; do sleep 100; done"]
        ports:
        - name: testing-web
          containerPort: 9000