---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cloudflaremon
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudflaremon
  namespace: ccc
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cloudflaremon
roleRef:
  kind: ClusterRole
  name: cloudflaremon
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: cloudflaremon
  namespace: ccc
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # This name uniquely identifies the Deployment
  name: testing-pod
  namespace: ccc
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        # Label is used as selector in the service.
        app: crab
        proc: testing
        k8s-app: testing
    spec:
      serviceAccount: cloudflaremon
      serviceAccountName: cloudflaremon
      containers:
      - name: base
        image: phusion/baseimage:0.9.22
        command: ["/sbin/my_init",  "--",  "bash",  "-c", "while true; do sleep 100; done"]
        ports:
        - name: testing-web
          containerPort: 9000