apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chameleon-master
  namespace: ccc
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: chameleon-master-webserver
        lang: js
    spec:
      containers:
      - name: chameleon-master
        image: registry.clickyab.ae/clickyab/chameleon:master.124
        envFrom:
        - configMapRef:
            name: crab-master-config
        volumeMounts:
        - name: statics
          mountPath: /usr/share/nginx/html/uploads
      volumes:
      - name: statics
        cephfs:
          monitors:
            - 192.168.10.1:6789
            - 192.168.10.6:6789
            - 192.168.10.11:6789
          user: admin
          secretRef:
            name: ceph-secret
          path: "/ccc/uploads"