apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: crab-swagger
  namespace: ccc
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: crab-swagger-webserver
        lang: js
    spec:
      containers:
      - name: swagger-master
        image: fzerorubigd/swagger-ui:latest
        envFrom:
        - configMapRef:
            name: crab-master-config