apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chameleon-master
  namespace: ccc
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: chameleon-master-webserver
        lang: js
    spec:
      containers:
      - name: chameleon-master
        image: registry.clickyab.ae/clickyab/chameleon:master.21
        envFrom:
        - configMapRef:
            name: crab-master-config