---
apiVersion: v1
kind: Service
metadata:
  name: testing
  namespace: ccc
  labels:
    k8s-app: testing
spec:
  selector:
    k8s-app: testing
  ports:
  - name: mster
    port: 9000
    protocol: TCP