---
apiVersion: extensions/v1beta1
kind: Service
apiVersion: v1
metadata:
  labels:
    service: redis
  name: redis
  namespace: ccc
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      name: redis