apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: crab-web-service
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: CrabMasterService
  name: crab-master-service
  namespace: ccc
  resourceVersion: "15773046"
  selfLink: /api/v1/namespaces/ccc/services/crab-master-service
  uid: b9015152-7cfb-11e7-8691-a4bf011e4d3a
spec:
  clusterIP: 10.111.229.249
  ports:
  - name: mster
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: mailhog
    port: 8025
    protocol: TCP
    targetPort: 8025
  selector:
    k8s-app: crab-master-webserver
