apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: testing
  namespace: ccc
spec:
  rules:
  - host: testing2.ccc.clickyab.ae
    http:
      paths:
      - backend:
          serviceName: testing
          servicePort: 9000
        path: /
