apiVersion: v1
data:
  CRB_CRAB_MODULES_UPLOAD_PATH: /statics/uploads
  CRB_SERVICES_FLUENTD_ALL_LEVELS: "true"
  CRB_SERVICES_FLUENTD_ENABLE: "true"
  CRB_SERVICES_FLUENTD_HOST: fluentd.elasticsearch
  CRB_SERVICES_FLUENTD_TAG: log.crab
  CRB_SERVICES_MYSQL_RDSN: root:qIxUnir2HOdorY055Ke6OK2CEs9Jiak4@tcp(crab-staging-mysqld-service.ccc:3306)/crab?charset=utf8&parseTime=true
  CRB_SERVICES_MYSQL_WDSN: root:qIxUnir2HOdorY055Ke6OK2CEs9Jiak4@tcp(crab-staging-mysqld-service.ccc:3306)/crab?charset=utf8&parseTime=true
  CRB_SERVICES_REDIS_ADDRESS: redis.ccc
  CRB_SERVICES_REDMINE_ACTIVE: "false"
  CRB_SERVICES_REDMINE_APIKEY: d924a953644dd1a339278a031c466210cf2b60fd
  CRB_SERVICES_REDMINE_NEW_ISSUE_TYPE_ID: "1"
  CRB_SERVICES_REDMINE_PROJECT_ID: "12"
  CRB_SERVICES_REDMINE_URL: http://tracker.clickyab.com
  CRB_SERVICES_SLACK_ACTIVE: T
  CRB_SERVICES_SLACK_CHANNEL: '#crab'
  CRB_SERVICES_SLACK_USERNAME: crab
  CRB_SERVICES_SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
  PORT: "9000"
  TIMEZONE: Asia/Tehran
  TZ: Asia/Tehran
  URL: http://staging.crab.clickyab.ae/api/misc/swagger/index.json
kind: ConfigMap
metadata:
  name: crab-master-config
  namespace: ccc
