---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ccc-master-ingress
  namespace: ccc
  annotations:
    ingress.kubernetes.io/proxy-body-size: 5m
spec:
  rules:
  - host: staging.crab.clickyab.ae
    http:
      paths:
      - path: /api
        backend:
          serviceName: crab-master-service
          servicePort: 8090
      - path: /
        backend:
          serviceName: chameleon-master-service
          servicePort: 80