apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: crab
    k8s-app: testing
    proc: testing
  name: testing-pod
  namespace: ccc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crab
      k8s-app: testing
      proc: testing
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: crab
        k8s-app: testing
        proc: testing
    spec:
      containers:
      - command:
        - /sbin/my_init
        - --
        - bash
        - -c
        - while true; do sleep 100; done
        image: phusion/baseimage:0.9.22
        imagePullPolicy: IfNotPresent
        name: base
        ports:
        - containerPort: 9000
          name: testing-web
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regsecret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
