apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: crab
    branch: master
    k8s-app: crab-master-webserver
    lang: go
    proc: webserver
  name: crab-master
  namespace: ccc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crab
      branch: master
      k8s-app: crab-master-webserver
      lang: go
      proc: webserver
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: crab
        branch: master
        k8s-app: crab-master-webserver
        lang: go
        proc: webserver
    spec:
      containers:
      - image: mailhog/mailhog
        imagePullPolicy: Always
        name: mailhog
        ports:
        - containerPort: 8025
          name: master-web
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - command:
        - /bin/bash
        - /app/bin/run_order.sh
        envFrom:
        - configMapRef:
            name: crab-master-config
        image: registry.clickyab.ae/clickyab/crab_master:309
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 5
        name: crab-master
        ports:
        - containerPort: 9000
          name: master-web
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/misc/swagger/index.json
            port: 9000
            scheme: HTTP
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            memory: 200Mi
          requests:
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /statics
          name: statics
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regsecret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - cephfs:
          monitors:
          - 192.168.10.1:6789
          - 192.168.10.6:6789
          - 192.168.10.11:6789
          path: /ccc
          secretRef:
            name: ceph-secret
          user: admin
        name: statics
