apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: mariadb
    k8s-app: zanata
    spec: zanatadb
  name: zanatadb
  namespace: ccc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
      k8s-app: zanata
      spec: zanatadb
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mariadb
        k8s-app: zanata
        spec: zanatadb
    spec:
      containers:
      - args:
        - --character-set-server=utf8
        - --collation-server=utf8_general_ci
        envFrom:
        - configMapRef:
            name: zanata-configmap
        image: mariadb:10.1
        imagePullPolicy: IfNotPresent
        name: zanatadb
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
