apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: crab-web-service
  name: crab-master-service
  namespace: ccc
spec:
  ports:
  - name: mster
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: mailhog
    port: 8025
    protocol: TCP
    targetPort: 8025
  selector:
    k8s-app: crab-master-webserver
