apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: chameleon-master-webserver
  name: chameleon-master-service
  namespace: ccc
spec:
  ports:
  - name: mster
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    k8s-app: chameleon-master-webserver
