apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: zanatadb-backup-cron
  namespace: ccc
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 12
  jobTemplate:
    spec:
      activeDeadlineSeconds: 1200
      template:
        spec:
          imagePullSecrets:
            - name: regsecret
          containers:
            - name: zantadb-backup
              envFrom:
                - configMapRef:
                    name: zanatadb-backup-config
              image: registry.clickyab.ae/clickyab/dbbackup-cron:latest
              resources:
                limits:
                  cpu: "1"
              volumeMounts:
                - name: ssh-keys
                  mountPath: /root/.ssh/
          volumes:
            - name: ssh-keys
              secret:
                secretName: ssh-key-secret
          restartPolicy: Never
  schedule: '0 0 * * *'
  successfulJobsHistoryLimit: 6
  suspend: false
