apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: chameleon-master-webserver
    lang: js
  name: chameleon-master
  namespace: ccc
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: chameleon-master-webserver
      lang: js
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: chameleon-master-webserver
        lang: js
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: crab-master-config
        image: registry.clickyab.ae/clickyab/chameleon_master:378
        imagePullPolicy: IfNotPresent
        name: chameleon-master
        resources:
          limits:
            memory: 200Mi
          requests:
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/nginx/html/uploads
          name: statics
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regsecret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - cephfs:
          monitors:
          - 192.168.10.1:6789
          - 192.168.10.6:6789
          - 192.168.10.11:6789
          path: /ccc/uploads
          secretRef:
            name: ceph-secret
          user: admin
        name: statics
