#!/usr/bin/env bash
set -x
set -eo pipefail

CA_LOCATION=${HOME}/clickyab/kubeaccess/kubernetes/pki
KEY_LOCATION=${HOME}/clickyab/kubeaccess
USER_NAME=${1:-}
TEAM=${2:-devteam}
NAMESPACE=${3:-ccc}
VALID_DAYS=${4:-60}

[ -z "$USER_NAME" ] && exit 1
mkdir -p ${KEY_LOCATION}/${USER_NAME}
pushd ${KEY_LOCATION}/${USER_NAME}
[ -f ${USER_NAME}.key ] || openssl genrsa -out ${USER_NAME}.key 2048
[ -f ${USER_NAME}.csr ] || openssl req -new -key ${USER_NAME}.key -out ${USER_NAME}.csr -subj "/CN=${USER_NAME}/O=${TEAM}"
openssl x509 -req -in ${USER_NAME}.csr -CA ${CA_LOCATION}/ca.crt -CAkey ${CA_LOCATION}/ca.key -CAcreateserial -out ${USER_NAME}.crt -days ${VALID_DAYS}

cat <<EOF >config
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFM01EY3hNVEU1TWpBeE1sb1hEVEkzTURjd09URTVNakF4TWxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSzlxCi9jWEFQTkhvNXBFTmJBOE10VlN1RC9LTnZubEtWSEU4elVJMTB0ei9hSGw2eWV1WnB0dG5HbThaOFFoRXhyRysKRHM0aEx2R3pnckpxaFl3T1V6WnFVWWFTUnVwWHo0cENuUVN4YVpjWktUWkY2WERGRDJLWG9jLzNBQ2NhbVEraQpXOVFZSWQ2WUtPN3lyN1haYzFnd3RqNnZnaS90a09TWXhZeXYvd0hpUUh6c1owMk1qNmNxUWJ1Njh1VEVMa2pTCnZqRDVXOGMwaWNpaGsvRnNXOHo0UldOekg0aHRYRlc3c1FMRFVEa24xQzFNUlNOR1ZsNG9pQURHRENBZ0NrVVQKKzRGamlFc3ZPZ3YwRFJQb3JrbWQxWFVqWXhJc2VkUkVZV3lRVUZGVXAzTWcvNHhCRVJPTkJNd1hzbE43bS9IQQpGSExsbDVlQ2RndEVFOUFlaWFNQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFHL3pHdW9Rd0g3YzFUejBhTjNnOUZ6Mlk0VEQKMkN3UGs4R3BlTDY4Vks0Ym16cTJyNVdFSXdEMUpIYTczc1NpSjhCUE4xRUEwbXB3T2ZpQmxScC9VNG90UGNHQwpkdC9KQ3hUSGszeU9pekY0RlJBdFVROXBkeWVmOWpCM3NJektNbkRzdHdQWlkzRWhNMzZBZ1NmZTFLbkZYeU9CCnFjakI0V1I0TmRBTVlEeEV5MWxMc2NzaU5jNzJiNXR6ZEZleUczd2VxOEFFdDI5cjA5TGN5OVhRYUs4ekgweFoKdUdOV0YxQ3RCeFBwajNCMEphcmJVczZRamkxNmFGakt5T2hxTTBsMmhuWWJxYlI0VFk5bFBXQ2pNbzVzU1FXRQo5L005ZXJxa1p5WVlyR3ZxTWVRODVXNWllN1NNNUVlTUNjNldFYTNzaFQwMjJEelBzbDVFYTRBUkJhdz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://5.135.142.71:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    namespace: ${NAMESPACE}
    user: ${USER_NAME}
  name: ${USER_NAME}-context
current-context: ${USER_NAME}-context
kind: Config
preferences: {}
users:
- name: ${USER_NAME}
  user:
    client-certificate: ${USER_NAME}.crt
    client-key: ${USER_NAME}.key
EOF


