---
apiVersion: v1
kind: Namespace
metadata:
  name: tools
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: tools
data:
  GF_SECURITY_ADMIN_USER: dpr
  GF_SECURITY_ADMIN_PASSWORD: AiB2choouePhu7Ah
  GF_USERS_ALLOW_SIGN_UP: "false"
