apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: analytics
    namespace: analytics
    service: mysqld
    type: db
  name: analytics-mysqld
  namespace: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics
      service: mysqld
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: analytics
        service: mysqld
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: analytics-mysqld-config
        image: registry.clickyab.ae/clickyab/mysqld-staging
        imagePullPolicy: Always
        name: mysqld
        ports:
        - containerPort: 3306
          name: msyqld
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql-datadir
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regsecret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
      volumes:
        - cephfs:
            monitors:
            - 192.168.10.1:6789
            - 192.168.10.6:6789
            - 192.168.10.11:6789
            path: /configs/analytics
            secretRef:
              name: ceph-secret
            user: admin
          name: mysql-datadir

