apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: pooya
subjects:
  - kind: ServiceAccount
    name: pooya
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: pooya
  apiGroup: rbac.authorization.k8s.io
