apiVersion: v1
kind: PersistentVolume
metadata:
  name: ceph-statics
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  rbd:
    monitors:
      - 192.168.100.60:6789
    pool: kubernetes
    image: statics
    user: admin
    secretRef:
      name: ceph-secret
    fsType: ext4
    readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: statics-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi