apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: confluence-ingress
  namespace: office
spec:
  rules:
  - host: docs.3rdad.com
    http:
      paths:
      - backend:
          serviceName: confluence-service
          servicePort: 8090
        path: /
