apiVersion: v1
data:
data:
  EXC_SERVICES_SLACK_ACTIVE: T
  EXC_SERVICES_SLACK_CHANNEL: '#octopus'
  EXC_SERVICES_SLACK_USERNAME: crab
  EXC_SERVICES_SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
  EXC_OCTOPUS_HOST_NAME: 'staging.exchange.clickyab.ae'
  EXC_SERVICES_AMQP_DSN: 'amqp://octopus_staging:44lVBoV7ws9mTsnPKpcgX4zYvIBcGg@rabbitmq.rabbitmq:5672/octopus_staging'
  EXC_SERVICES_AMQP_EXCHANGE: 'third'
  EXC_SERVICES_BROKER_PROVIDER: 'rabbitmq'
  EXC_SERVICES_MYSQL_MAX_CONNECTION: '100'
  EXC_SERVICES_MYSQL_RDSN: 'root:Kc6Pvepk3YTehm6gxvPhCCVE4OqdjZ@tcp(mysqld-service.octopus-staging:3306)/octopus?charset=utf8&parseTime=true'
  EXC_SERVICES_MYSQL_WDSN: 'root:Kc6Pvepk3YTehm6gxvPhCCVE4OqdjZ@tcp(mysqld-service.octopus-staging:3306)/octopus?charset=utf8&parseTime=true'
  EXC_SERVICES_REDIS_ADDRESS: 'redis.octopus-staging:6379'
  # EXC_SERVICES_REDIS_DB: '5'
  # EXC_SERVICES_REDIS_PASSWORD: 'bita123'
  EXC_SERVICES_SLACK_ACTIVE: 'true'
  EXC_SERVICES_SLACK_WEBHOOK_URL: 'https://hooks.slack.com/services/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'
  RABBITMQ_URL: 'amqp://octopus_staging:44lVBoV7ws9mTsnPKpcgX4zYvIBcGg@rabbitmq.rabbitmq:5672/octopus_staging'
  PORT: '9000'
kind: ConfigMap
metadata:
  name: octopus-staging-config
  namespace: octopus-staging
