apiVersion: v1
kind: Service
metadata:
  name: rtbsupplier-service
  namespace: octopus-staging
  labels:
    k8s-app: rtbsupplier-service
spec:
  selector:
    spec: rtbsupplier
  ports:
  - name: rtbsupplier
    port: 9000
    protocol: TCP
