apiVersion: v1
kind: Service
metadata:
  name: mysqld-service
  namespace: octopus-staging
  labels:
    k8s-app: octopus-staging
    app: octopus
    service: mysqld
    branch: dev
    type: db
    namespace: octopus-staging
spec:
  selector:
    service: mysqld
  ports:
    - name: mysqld
      port: 3306
      protocol: TCP
