apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rtbdemand-ingress
  namespace: octopus-staging
spec:
  rules:
  - host: staging.exchange.clickyab.ae
    http:
      paths:
      - path: /rtbdem
        backend:
          serviceName: rtbdemand-service
          servicePort: 9000
