apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rtbsupplier-ingress
  namespace: octopus-staging
spec:
  rules:
  - host: staging.exchange.clickyab.ae
    http:
      paths:
      - path: /rtbsup
        backend:
          serviceName: rtbsupplier-service
          servicePort: 9000
